version: "3.9"
services:
  docker-html-sample1:
    image: santhoshprogrammer94/docker-html-sample:v1
    ports:
      - "5050:80"
  docker-html-sample2:
    image: santhoshprogrammer94/docker-html-sample:v1
    ports:
     - "5051:80"